#DEPLOYMENT 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    tier: backend
spec:
  replicas: 1 
  selector:
    matchLabels:  
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: my-new-container
        image: httpd
        ports:
          - containerPort: 80
      