kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane  # Master node
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
  - role: worker          # Worker node 1
  - role: worker          # Worker node 2
