apiVersion: apps/v1
kind:  Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
      
    spec:
      containers:
      - image: nginx
        name: nginc-container
        ports:
        - containerPort: 80
