apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: backend
spec:
  replicas: 5  # ✅ Correct placement of replicas
  selector:
    matchLabels:  # ✅ Selector added
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: my-new-container
        image: nginx:1.23.4
      